<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

$root_dir = dirname(__DIR__);
$webroot_dir = $root_dir . '/web';


/**
 * Use Dotenv to set required environment variables and load .env file in root
 */
$dotenv = new Dotenv\Dotenv($root_dir);
if (file_exists($root_dir . '/.env')) {
  $dotenv->load();
}

/**
 * URLs
 */
define('WP_HOME', $_ENV['WP_HOME']);
define('WP_SITEURL', $_ENV['WP_SITEURL']);
/**
 * Custom Content Directory
 */
define('CONTENT_DIR', '/app');
define('WP_CONTENT_DIR', $webroot_dir . CONTENT_DIR);
define('WP_CONTENT_URL', WP_HOME . CONTENT_DIR);

define('DB_NAME', $_ENV['DB_NAME']);

/** MySQL database username */
define('DB_USER', $_ENV['DB_USER']);

/** MySQL database password */
define('DB_PASSWORD', $_ENV['DB_PASSWORD']);

/** MySQL hostname */
define('DB_HOST', $_ENV['DB_HOST']);

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/*AWS Access Keys*/
if($_ENV["AWS_KEY_ID"] && $_ENV["AWS_SECRET_ACCESS_KEY"]){
	define( 'DBI_AWS_ACCESS_KEY_ID', $_ENV["AWS_KEY_ID"]);	
	define( 'DBI_AWS_SECRET_ACCESS_KEY', $_ENV["AWS_SECRET_ACCESS_KEY"]);
}

/**#@+
* Authentication Unique Keys and Salts.
*
* Change these to different unique phrases!
* You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
* You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
*
* @since 2.6.0
*/
define('AUTH_KEY',         '~dhJ#[A#B4BAzvnd-fU#8n,sL$RD(r;+o|qMo<)NZ;P_K5jG)nYr/6bE]A }1<]`');
define('SECURE_AUTH_KEY',  ';P(j)pD:&e<ZEvu~)ZCYO}%`migp|7ZpB?ML=eTJL!=(`yhGVT#{ZWZ+Q*MPu-Fm');
define('LOGGED_IN_KEY',    '*<J83k5oh3?b!Teu.rH=LFe;$*[.wWZ=]M8Y1]NF@%$t)Po=a_MD=jF>hJ&zBL2c');
define('NONCE_KEY',        '=9F).%H[F|+)/v&pC!p2T<.UW?H<wZr$$joXV-N1.Q,!3zb9{?E@rF2vi[2%r:0|');
define('AUTH_SALT',        '~#cE>Eg>?Tk$M%!dX>mi{~2if_f~yOfq`4@DuHJu[gYd!L6qQ|[XQn~Qk];}q#6z');
define('SECURE_AUTH_SALT', 'TqP5&t/DYQ=.i|>VbDMuq_Uky/OrS@S{22q$*d?z&ti5m4kp%zi3b<mc<PmCv%}e');
define('LOGGED_IN_SALT',   '>xo77]d?g=[`{ps|/JQMx,U|//=99.o_A&^W`!Oq5FvYxMtv8:FDh(~ 0V`8G7,>');
define('NONCE_SALT',       'PwRZLe;t6ls]kR?;}GU;g[[]&bG@^^|vApY1vn7OV+lOmv>CEh0$H4copUYJ[)JK');
/**#@-*/

/**
* WordPress Database Table prefix.
*
* You can have multiple installations in one database if you give each a unique
* prefix. Only numbers, letters, and underscores please!
*/
$table_prefix  = 'wp_';

/**
* WordPress Localized Language, defaults to English.
*
* Change this to localize WordPress.  A corresponding MO file for the chosen
* language must be installed to wp-content/languages. For example, install
* de.mo to wp-content/languages and set WPLANG to 'de' to enable German
* language support.
*/
define ('WPLANG', '');
define ('WP_CACHE', false);
/**
* For developers: WordPress debugging mode.
*
* Change this to true to enable the display of notices during development.
* It is strongly recommended that plugin and theme developers use WP_DEBUG
* in their development environments.
*/
define('SAVEQUERIES', false);
define('WP_DEBUG', false/*$_ENV['DEBUG_WP']*/);
define('SCRIPT_DEBUG', false/*$_ENV['DEBUG_SCRIPTS']*/);
define('WP_DEBUG_LOG', false/*$_ENV['DEBUG_WP_LOG']*/);

/* That's all, stop editing! Happy blogging. */

/**
 * Bootstrap WordPress
 */
if (!defined('ABSPATH')) {
  define('ABSPATH', $webroot_dir . '/wp/');
}

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
